Don't write to defaults dir but to local

diff --git a/bin/bigpanda-splunk-defaults b/bin/bigpanda-splunk-defaults
--- a/bin/bigpanda-splunk-defaults
+++ b/bin/bigpanda-splunk-defaults
@@ -39,6 +39,17 @@ action.script.filename = bigpanda-splunk
 EOF
 }
 
+function write_configuration_file {
+    echo "INFO:  writing configuration file to $CONFIGURATION_FILE"
+    sudo tee $CONFIGURATION_FILE << EOF >> /dev/null
+####################
+#     BigPanda     #
+####################
+action.script = 1
+action.script.filename = bigpanda-splunk
+EOF
+}
+
 case "$1" in
     -h|--help)
         usage
@@ -54,41 +65,46 @@ while true; do
 done
 
 SPLUNK_HOME=${1:-/opt/splunk}
-CONFIGURATION_FILE=$SPLUNK_HOME/etc/system/default/savedsearches.conf
+CONFIGURATION_FILE=$SPLUNK_HOME/etc/system/local/savedsearches.conf
 
 echo "INFO:  Splunk home is $SPLUNK_HOME. Configuring BigPanda in $CONFIGURATION_FILE"
 
 if [ ! -f $CONFIGURATION_FILE ]; then
-    echo "ERROR:  Couldn't find configuration file at path $CONFIGURATION_FILE"
-    exit 1
-fi
-
-# Grant write permissions to user Splunk before changing the configuration file
-if ! chmod u+w $CONFIGURATION_FILE; then
-    echo "ERROR:  Failed to give write permissions on $CONFIGURATION_FILE"
-    exit_after_chmod 1
-fi
-
-# Enable the script action by default for all alerts (existing and new)
-if grep -i --silent "action.script\s*=\s*1" $CONFIGURATION_FILE; then
-    echo "WARN:  action.script is already enabled."
+    write_configuration_file
+    chown splunk:splunk $CONFIGURATION_FILE
+    chmod 0444 $CONFIGURATION_FILE
 else
-    echo "INFO:  Enabling action.script by default for all alerts"
-    sudo -u splunk sed -i.bak '/^action.script *= *0$/ s/0/1/' $CONFIGURATION_FILE
-fi
-
-# Make sure action.script.filename was not already configured
-if grep -i --silent "action.script.filename" $CONFIGURATION_FILE; then
-    # Make sure we're not grepping our own configuration
-    if grep -i --silent "action.script.filename\s*=.*bigpanda.*" $CONFIGURATION_FILE; then
-        already_configured
-    else
-        echo "ERROR:  action.script.filename is already configured. Contact support@bigpanda.io for details on how to configure an existing action script."
+    # Grant write permissions to user Splunk before changing the configuration file
+    if ! chmod u+w $CONFIGURATION_FILE; then
+        echo "ERROR:  Failed to give write permissions on $CONFIGURATION_FILE"
         exit_after_chmod 1
     fi
+
+    # Enable the script action by default for all alerts (existing and new)
+    if grep -i --silent "action.script\s*=\s*1" $CONFIGURATION_FILE; then
+        echo "WARN:  action.script is already enabled."
+    else
+        echo "INFO:  Enabling action.script by default for all alerts"
+        sudo -u splunk sed -i.bak '/^action.script *= *0$/ s/0/1/' $CONFIGURATION_FILE
+    fi
+
+    # Make sure action.script.filename was not already configured
+    if grep -i --silent "action.script.filename" $CONFIGURATION_FILE; then
+        # Make sure we're not grepping our own configuration
+        if grep -i --silent "action.script.filename\s*=.*bigpanda.*" $CONFIGURATION_FILE; then
+            already_configured
+        else
+            echo "ERROR:  action.script.filename is already configured. Contact support@bigpanda.io for details on how to configure an existing action script."
+            exit_after_chmod 1
+        fi
+    fi
+
+    configure_script_filename
+
 fi
 
-configure_script_filename
-
 exit_after_chmod 0
+
+
+
 
