1. Check for root privileges 2. Remove redundant sudo

diff --git a/bin/bigpanda-splunk-defaults b/bin/bigpanda-splunk-defaults
--- a/bin/bigpanda-splunk-defaults
+++ b/bin/bigpanda-splunk-defaults
@@ -28,7 +28,7 @@ function already_configured {
 
 function configure_script_filename {
     echo "INFO:  Setting bigpanda-splunk as default script"
-    sudo tee -a $CONFIGURATION_FILE << EOF >> /dev/null
+    cat << EOF >> $CONFIGURATION_FILE
 
 ####################
 #     BigPanda     #
@@ -39,7 +39,7 @@ EOF
 
 function write_configuration_file {
     echo "INFO:  writing configuration file to $CONFIGURATION_FILE"
-    sudo -u splunk tee $CONFIGURATION_FILE << EOF >> /dev/null
+    cat << EOF >> $CONFIGURATION_FILE
 ####################
 #     BigPanda     #
 ####################
@@ -53,6 +53,12 @@ case "$1" in
         usage
         ;;
 esac
+
+MY_UID=`id | awk '{ print $1 }'`
+if [ "${MY_UID}" != "uid=0(root)" ] ; then
+    echo "ERROR:  You must run this script with root privileges"
+    exit 1
+fi
 
 while true; do
     read -p "Do you want to set all your Splunk alerts to be sent to BigPanda by default? [y/n]" yn
@@ -69,6 +75,7 @@ echo "INFO:  Splunk home is $SPLUNK_HOME. Configuring BigPanda in $CONFIGURATION
 
 if [ ! -f $CONFIGURATION_FILE ]; then
     write_configuration_file
+    chown splunk:splunk $CONFIGURATION_FILE
     chmod 0600 $CONFIGURATION_FILE
 else
 
@@ -78,10 +85,10 @@ else
         echo "action.script = 1" >> $CONFIGURATION_FILE
     else
         if grep -i --silent "action.script\s*=\s*1" $CONFIGURATION_FILE; then
-            echo "WARN:  action.script is already enabled."
+            echo "INFO:  action.script is already enabled."
         else
             echo "INFO:  Enabling action.script by default for all alerts"
-            sudo -u splunk sed -i.bak '/^action.script *= *0$/ s/0/1/' $CONFIGURATION_FILE
+            sed -i.bak '/^action.script *= *0$/ s/0/1/' $CONFIGURATION_FILE
         fi
     fi
 
